"""empty message

Revision ID: 474bf45956b6
Revises: 
Create Date: 2022-03-28 16:50:01.034893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474bf45956b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_house_facility', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_house_facility', 'id')
    # ### end Alembic commands ###
